development:
  adapter: postgresql
  encoding: unicode
  database: escape_development
  pool: 5
  username: escape
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: escape_test
  pool: 5
  username: escape
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: escape_production
  pool: 5
  username: escape
  password:

