FoursquareImporter:
  cron: "*/5 * * * *"
  queue: foursquare_queue

TwitterImporter:
  cron:  "*/5 * * * *"
  queue: twitter_queue

InstagramImporter:
  cron:  "*/5 * * * *"
  queue: instagram_queue
